### PR TITLE
RTDSDK-1709

### PR DESCRIPTION
**Pull request by anpur**
- Splitting Retrier and Backoff to different files
 - Handling maxDelay
 - Fixing warnings in package.json

### CODE REVIEW

**Comment by aleksandrsivanovs** [comment]
split to two files is breaking change - all deps would break. 
please bump version to 3.0

**Comment by adrianObel** [comment]
Posting this here from lack of a better option - this release seems to have broken `twilio-chat`. 

The dependency was set as `latest` and that's being problematic for obvious reasons

**Comment by aleksandrsivanovs** [comment]
thank you for your report, we fixed the "latest" in the new version and this slipped through.
will do the hotfix release for the operation-retrier soon enough

**Comment by aleksandrsivanovs** [comment]
work is going on here: https://github.com/twilio/operation-retrier.ts/tree/fix-backwards-compatibility

**Comment by aleksandrsivanovs** [comment]
@adrianObel this is fixed in 3.0.1 release:
https://github.com/twilio/operation-retrier.ts/releases/tag/release-3.0.1
https://www.npmjs.com/package/operation-retrier/v/3.0.1

please re-verify that your code now works (twilio-chat will pick up latest version)

**Comment by adrianObel** [comment]
@aleksandrsivanovs confirmed that the issue has been resolved. Thank you for the quick action :)

**Pull request merged**
